### ISSUE TITLE
Pre-existing lockers not working after kernel update

### ISSUE THREAD

**Issue by marvinmarnold** [locker-labs/locker-ui#46]
Locker recently upgraded the underlying ZeroDev smart account code (AKA "kernel") that we are using. This was necessary in order to unlock more granular permissions functionality to keep your lockers safe.

But this means that if you used Locker initially, your old accounts are now in a corrupt state. 

Waiting for answers on Discord support about best way to handle this. https://discord.com/channels/1049721098327044186/1050489343220908092/1266414161911484436

**Comment by marvinmarnold** [comment]
https://discord.com/channels/1049721098327044186/1050489343220908092/1268228106942939177

<img width="484" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkV0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4f6ea8e540fed3bfba10d5d72a0765f65a6bee9/Screenshot%202024-08-02%20at%209.24.41%20PM.png" alt="Screenshot 2024-08-02 at 9.24.41 PM.png" />

**Comment by marvinmarnold** [comment]
@bilgute basically it's not yet possible to upgrade lockers from older versions. In the future, we will need a way to migrate funds from old lockers to new ones or to continue using old lockers with limited features. 

What do you think the best way to handle this now is? I'd like to just announce in Telegram and let people know Locker will reimburse. Because we are still in closed beta, there's a very small amount of test funds that I don't think people care about.

Alternatively, I could make a small app so users can transfer funds out of the old lockers. But unless someone asks, doesn't seem necessary.

**Comment by bilgute** [comment]
Hi Marvin, thanks mate for keeping me updated.
I also think it is not necessary at the moment.
